### ISSUE TITLE
Cannot find module './style'

### ISSUE THREAD

**Issue by tennety** [medikoo/bespoke-notes#2]
I'm working on a newly generated bespoke presentation and wanted to use the notes plugin. When I run `gulp serve` I get the following error:

```
Error: module "./style" not found from "/Users/tennety/Documents/presos/stirtrek-2016/node_modules/bespoke-notes/index.js"
    at notFound (/Users/tennety/Documents/presos/stirtrek-2016/node_modules/gulp-browserify/node_modules/browserify/index.js:803:15)
    at /Users/tennety/Documents/presos/stirtrek-2016/node_modules/gulp-browserify/node_modules/browserify/index.js:754:23
    at /Users/tennety/Documents/presos/stirtrek-2016/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
```

Am I missing something?

**Comment by medikoo** [comment]
Sorry for not clear usage instructions, it works out of a box if CJS bundler supports `.css` modules, otherwise you need to require `bespoke-notes/dom` instead, and some other way ensure that style rules that are in `style.css` are loaded by your browser

I've improved usage notes in README.md so hopefully it won't be that confusing anymore

**Comment by tennety** [comment]
Awesome! Thanks and thanks for your work on bespoke-notes!
